[tool.poetry]
name = "vision"
version = "0.1.0"
description = ""
authors = ["Nicholas Chiang <nicholas.h.chiang@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
instagrapi = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
